{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "account-api.fullname" . }}-secrets
  labels:
    {{- include "account-api.labels" . | nindent 4 }}
spec:
  provider: {{ .Values.secretProvider.provider }}
  parameters:
    keyvaultName: "{{ .Values.secretProvider.keyvault.name }}"
    tenantId: "{{ .Values.secretProvider.keyvault.tenantId }}"
    usePodIdentity: "true"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.secretProvider.keyvault.identityId }}"
    objects: |
      array:
        {{- range .Values.secretProvider.secrets }}
        - |
          objectName: {{ .objectName }}
          objectAlias: {{ .name }}
          objectType: secret
        {{- end }}
  secretObjects:
  - data:
      {{- range .Values.secretProvider.secrets }}
      - objectKey: {{ .name }}
        key: {{ .name }}
      {{- end }}
    secretName: {{ include "account-api.fullname" . }}-secrets
    type: Opaque
{{- end }}
