apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sms-api.fullname" . }}-config
  labels:
    {{- include "sms-api.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ (index .Values.env 0).value | quote }}
  TWILIO_APP_PHONE: {{ (index .Values.env 2).value | quote }}
  NODE_ENV: {{ (index .Values.env 3).value | quote }}
  AUTH_API_URL: {{ (index .Values.env 4).value | quote }}
