apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "geo-api.fullname" . }}
  labels:
    {{- include "geo-api.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "true"
    keyvaultName: kv-rewn-prod-cin
    tenantId: "{{ .Values.global.tenantId | default \"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\" }}"
    objects: |
      array:
        - |
          objectName: geo-api-redis-password
          objectAlias: redis-password
          objectType: secret
        - |
          objectName: geo-api-auth-secret
          objectAlias: auth-secret
          objectType: secret
  secretObjects:
    - secretKey: redis-password
      objectName: redis-password
      data: |-
        redis-password
    - secretKey: auth-secret
      objectName: auth-secret
      data: |-
        auth-secret
  resources:
    requests:
      storage: 1Gi
