apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rewn-chat.serviceAccountName" . }}
  labels:
    {{- include "rewn-chat.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rewn-chat.fullname" . }}-role
  labels:
    {{- include "rewn-chat.labels" . | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rewn-chat.fullname" . }}-rolebinding
  labels:
    {{- include "rewn-chat.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rewn-chat.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "rewn-chat.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
