apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rewn-fastapi.fullname" . }}
  labels:
    {{- include "rewn-fastapi.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rewn-fastapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rewn-fastapi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rewn-fastapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: rewn-fastapi
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          {{- toYaml .Values.healthCheck.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.healthCheck.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        # Secrets from ConfigMap and Secret
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "rewn-fastapi.fullname" . }}
              key: redis-password
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "rewn-fastapi.fullname" . }}
              key: mongo-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "rewn-fastapi.fullname" . }}
              key: mysql-password
        - name: OLLAMA_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "rewn-fastapi.fullname" . }}
              key: ollama-api-key
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-run
          mountPath: /var/run
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-run
        emptyDir: {}
