apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mail-manager-api.fullname" . }}-config
  labels:
    {{- include "mail-manager-api.labels" . | nindent 4 }}
data:
  # Internal API endpoints
  data-api-url: {{ .Values.config.dataApiUrl }}
  account-api-url: {{ .Values.config.accountApiUrl }}
  sci-net-url: {{ .Values.config.sciNetUrl }}
  motivated-api-url: {{ .Values.config.motivatedApiUrl }}
  
  # Redis Configuration
  redis-host: {{ .Values.config.redisHost }}
  redis-port: {{ .Values.config.redisPort | quote }}
  
  # MongoDB Configuration
  db-hosts: {{ .Values.config.dbHosts }}
  db-username: {{ .Values.config.dbUsername }}
  
  # Logging
  logging-level: {{ .Values.config.logLevel }}
  
  # Environment
  node-env: {{ .Values.config.nodeEnv }}
