apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mail-manager-api.serviceAccountName" . }}
  labels:
    {{- include "mail-manager-api.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mail-manager-api.fullname" . }}-role
  labels:
    {{- include "mail-manager-api.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - {{ include "mail-manager-api.fullname" . }}-secrets
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames:
      - {{ include "mail-manager-api.fullname" . }}-config
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mail-manager-api.fullname" . }}-rolebinding
  labels:
    {{- include "mail-manager-api.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mail-manager-api.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "mail-manager-api.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
